name: flutter_img_editor
description: "Image_editor is an embeddable Flutter image editing component that offers common editing tools such as cropping, rotating, and text overlay."
version: 0.0.2
homepage: https://github.com/xinqingaa/flutter_img_editor
repository: https://github.com/xinqingaa/flutter_img_editor


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

